# Generated by Django 6.0.3 on 2026-04-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='textmodel',
            name='text_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='text_content',
            field=models.TextField(db_index=True),
        ),
    ]
